# Generated by Django 4.1.2 on 2023-07-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactenquiry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactenquiry",
            name="email",
            field=models.EmailField(max_length=50),
        ),
    ]
