# Generated by Django 4.1.2 on 2023-07-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emailenquiry", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailenquiry",
            old_name="email",
            new_name="email_id",
        ),
    ]
